### ISSUE TITLE
Milestone 3 presentation

### ISSUE THREAD

**Issue by SaadiaJameel** [cepdnaclk/e18-3yp-Automated-Road-Rule-Detector#15]
- [x] Make the slides
- [x] Add a progress video
- [x] Update the project page, etc
